version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: omsdemo
      POSTGRES_DB: hojaega_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hojaega_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Use production Dockerfile
    container_name: hojaega-backend
    environment:
      DATABASE_URL: postgres://postgres:omsdemo@db:5432/hojaega_db
    volumes:
      - screenshots:/app/screenshots
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:latest
    container_name: hojaega_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  pgdata:
  screenshots:
  caddy_data:
  caddy_config:
