services:
  - type: web
    name: hojaega-backend
    env: node
    plan: free
    buildCommand: npm run render:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
    healthCheckPath: /health
